/* ─────────────────────────────────────────────────
   DATA
───────────────────────────────────────────────── */
export const SERVICES = [
  {
    id: "education",
    number: "01",
    icon: "🎓",
    name: "Education",
    tagline: "Transforming\nLearning Across\nAfrica",
    sub: "Delivering transformative learning experiences across South Africa. We partner with institutions and learners to bridge knowledge gaps and empower communities through quality education.",
    accentColor: "rgba(29,158,117,0.15)",
    accentColorStrong: "rgba(29,158,117,0.08)",
    overview: [
      "At Ace Group Education, we believe that <strong>access to quality learning is a fundamental right</strong>, not a privilege. Our division partners with schools, universities, training institutions, and corporates to reshape how knowledge is delivered and absorbed across South Africa.",
      "We combine curriculum expertise with operational excellence, ensuring that our programmes are not just well-designed but <strong>measurably effective</strong>. From foundational literacy to professional certification, we serve every stage of the learning journey.",
      "Our approach is rooted in the belief that education must be <strong>contextual, relevant, and empowering</strong> — designed for the real challenges facing South African learners today, and the global opportunities of tomorrow.",
    ],
    pillars: [
      { icon: "📚", title: "Curriculum Design", text: "World-class learning frameworks aligned to South African and international standards." },
      { icon: "🏫", title: "Institution Partnerships", text: "Deep collaboration with schools, colleges, and training centres to elevate quality." },
      { icon: "🌍", title: "Community Impact", text: "Education programmes designed to uplift entire communities, not just individual learners." },
    ],
    offerings: [
      { title: "K-12 Academic Support", text: "Supplementary and core learning resources for primary and secondary learners." },
      { title: "Professional Certification", text: "Industry-recognised programmes for working professionals seeking to upskill." },
      { title: "Corporate Training", text: "Bespoke learning solutions designed for organisational capability building." },
      { title: "Curriculum Consulting", text: "Helping institutions redesign courses for impact, compliance, and relevance." },
      { title: "Learnerships & Internships", text: "Structured pathways bridging academic education with workplace readiness." },
      { title: "Assessment Solutions", text: "Rigorous, fair, and adaptive assessment tools for learners at every level." },
    ],
    stats: [
      { num: "5+", label: "Programme Types" },
      { num: "SA", label: "National Reach" },
      { num: "2024", label: "Established" },
      { num: "∞", label: "Lives to Impact" },
    ],
    quote: "Education is the most powerful weapon you can use to change the world — and we are building the arsenal.",
    quoteAttr: "Ace Group Education · Mission Statement",
    desc: "Delivering transformative learning experiences across South Africa.",
  },
  {
    id: "software",
    number: "02",
    icon: "💻",
    name: "Software Development",
    tagline: "Engineering\nThe Future,\nLine by Line",
    sub: "Building bespoke software solutions from concept to deployment. Our engineers craft scalable, high-performance applications tailored to the unique needs of African and global markets.",
    accentColor: "rgba(55,138,221,0.15)",
    accentColorStrong: "rgba(55,138,221,0.08)",
    overview: [
      "Ace Group Software Development is where <strong>ideas are transformed into intelligent, scalable systems</strong>. Our engineering teams design and build custom software solutions that don't just meet requirements — they anticipate them.",
      "We understand that African markets have <strong>unique infrastructure realities and user needs</strong>. We build with this in mind: optimising for low-bandwidth environments, designing intuitive interfaces for diverse user groups, and creating systems that are resilient in the face of real-world constraints.",
      "From MVPs to enterprise-grade platforms, our team brings <strong>full-stack capability, product thinking, and deep technical rigour</strong> to every project.",
    ],
    pillars: [
      { icon: "⚙️", title: "Full-Stack Engineering", text: "End-to-end development from database architecture to polished user interfaces." },
      { icon: "☁️", title: "Cloud & Infrastructure", text: "Scalable, secure cloud deployments on AWS, Azure, and Google Cloud." },
      { icon: "🔒", title: "Security by Design", text: "Every system we build has security baked in from the very first line of code." },
    ],
    offerings: [
      { title: "Custom Web Applications", text: "Bespoke web platforms built for performance, scale, and user delight." },
      { title: "Mobile Development", text: "Native and cross-platform apps for iOS and Android that users love." },
      { title: "API & Integration", text: "Robust APIs and third-party integrations that connect your ecosystem." },
      { title: "Enterprise Systems", text: "Mission-critical software for large organisations, built to last decades." },
      { title: "DevOps & CI/CD", text: "Automated deployment pipelines that let teams ship faster with confidence." },
      { title: "Legacy Modernisation", text: "Breathing new life into aging systems without disrupting operations." },
    ],
    stats: [
      { num: "100%", label: "Custom Built" },
      { num: "24/7", label: "System Uptime Focus" },
      { num: "2024", label: "Established" },
      { num: "0→1", label: "MVP Specialists" },
    ],
    quote: "Great software is invisible. Users don't think about it — they just accomplish things they couldn't before.",
    quoteAttr: "Ace Group Software · Engineering Philosophy",
    desc: "Building bespoke software solutions from concept to deployment.",
  },
  {
    id: "ai",
    number: "03",
    icon: "🤖",
    name: "AI & Automation Engineering",
    tagline: "Machines That\nThink, Systems\nThat Scale",
    sub: "Harnessing the power of artificial intelligence to automate processes, enhance decision-making, and unlock new value across industries. Future-ready systems built for today.",
    accentColor: "rgba(122,58,201,0.15)",
    accentColorStrong: "rgba(122,58,201,0.08)",
    overview: [
      "Ace Group AI & Automation Engineering sits at the <strong>frontier of what's possible</strong>. We design and deploy intelligent systems that learn, adapt, and optimise — transforming how businesses operate across every sector.",
      "We don't believe in AI for its own sake. Every model we build, every automation we deploy is <strong>anchored to a real business outcome</strong>. Our approach begins with deep problem understanding, moves through rigorous data strategy, and culminates in production systems that deliver measurable ROI.",
      "From natural language processing to computer vision, from robotic process automation to predictive analytics — our team brings <strong>research-grade capability to commercial-grade implementation</strong>.",
    ],
    pillars: [
      { icon: "🧠", title: "Machine Learning", text: "Custom ML models trained on your data to solve your specific challenges." },
      { icon: "🔄", title: "Process Automation", text: "Eliminating repetitive tasks with intelligent RPA and workflow automation." },
      { icon: "📊", title: "Predictive Analytics", text: "Turning historical data into actionable foresight for smarter decisions." },
    ],
    offerings: [
      { title: "Large Language Models", text: "Custom LLM deployments and fine-tuning for domain-specific applications." },
      { title: "Computer Vision", text: "Image and video analysis systems for quality control, security, and insight." },
      { title: "Chatbots & Virtual Agents", text: "Intelligent conversational systems that handle complex customer interactions." },
      { title: "Data Engineering", text: "Building the data pipelines and infrastructure that power great AI." },
      { title: "RPA Solutions", text: "Robotic process automation to eliminate manual, repetitive work at scale." },
      { title: "AI Strategy Consulting", text: "Helping organisations identify, prioritise, and execute their AI roadmap." },
    ],
    stats: [
      { num: "AI", label: "Native Capability" },
      { num: "∞", label: "Automation Potential" },
      { num: "2024", label: "Established" },
      { num: "100%", label: "Outcome Focused" },
    ],
    quote: "Artificial intelligence is not replacing human judgement — it is amplifying it. We build the amplifier.",
    quoteAttr: "Ace Group AI · Vision Statement",
    desc: "Harnessing AI to automate processes and enhance decision-making.",
  },
  {
    id: "ehailing",
    number: "04",
    icon: "🚗",
    name: "eHailing & Transportation",
    tagline: "Moving South\nAfrica Forward,\nTogether",
    sub: "Modernising mobility across South Africa. Our transport solutions connect drivers and passengers through intelligent, reliable, and affordable eHailing technology.",
    accentColor: "rgba(201,151,58,0.15)",
    accentColorStrong: "rgba(201,151,58,0.08)",
    overview: [
      "Ace Group eHailing & Transportation is redefining how South Africans move. We believe that <strong>safe, reliable, and affordable mobility</strong> is a cornerstone of economic participation — and we're building the technology to make it real.",
      "Our platform is designed from the ground up for the <strong>realities of South African roads, networks, and communities</strong>. We understand load-shedding, data costs, and the diversity of our driver and passenger base — and we build accordingly.",
      "Beyond the ride, we are building an <strong>ecosystem that empowers drivers</strong> as micro-entrepreneurs, provides passengers with genuine peace of mind, and contributes to the formalisation of the transport sector.",
    ],
    pillars: [
      { icon: "🗺️", title: "Intelligent Routing", text: "Smart matching and routing algorithms optimised for South African road conditions." },
      { icon: "🛡️", title: "Safety First", text: "Multi-layer safety features protecting both drivers and passengers on every trip." },
      { icon: "💰", title: "Driver Empowerment", text: "Fair earnings structures and tools that help drivers build sustainable income." },
    ],
    offerings: [
      { title: "Passenger eHailing App", text: "Seamless ride booking with real-time tracking and multiple payment options." },
      { title: "Driver Platform", text: "A driver-first app with earnings tracking, navigation, and support tools." },
      { title: "Corporate Transport", text: "Managed mobility solutions for businesses needing reliable staff transport." },
      { title: "Fleet Management", text: "Technology tools for transport operators to manage and optimise their fleets." },
      { title: "Freight & Delivery", text: "Last-mile logistics and delivery services powered by our transport network." },
      { title: "Safety Infrastructure", text: "Real-time monitoring, emergency response, and driver verification systems." },
    ],
    stats: [
      { num: "SA", label: "Operating Region" },
      { num: "24/7", label: "Platform Availability" },
      { num: "2024", label: "Established" },
      { num: "→∞", label: "Cities to Serve" },
    ],
    quote: "Every journey matters. Every driver deserves dignity. Every passenger deserves safety. That's why we build.",
    quoteAttr: "Ace Group Transport · Purpose Statement",
    desc: "Connecting drivers and passengers through intelligent, reliable eHailing technology.",
  },
  {
    id: "edtech",
    number: "05",
    icon: "📱",
    name: "Educational Technology",
    tagline: "Where Learning\nMeets the\nDigital Age",
    sub: "Where education meets innovation. We develop EdTech platforms that make learning accessible, engaging, and measurable — powering the next generation of digital learners.",
    accentColor: "rgba(201,58,58,0.12)",
    accentColorStrong: "rgba(201,58,58,0.07)",
    overview: [
      "Ace Group Educational Technology bridges the gap between <strong>pedagogical excellence and digital innovation</strong>. We build platforms, tools, and ecosystems that transform how learners engage with knowledge — making education more accessible, more measurable, and more human.",
      "We believe that technology in education should be <strong>invisible in the best way possible</strong> — removing friction, surfacing insights, and enabling educators to do what they do best. Our platforms are built for teachers as much as for students.",
      "From adaptive learning engines to learner management systems, from gamified content to data-driven progress tracking — our EdTech division is <strong>reimagining the architecture of learning</strong> for a connected South Africa.",
    ],
    pillars: [
      { icon: "🎮", title: "Gamified Learning", text: "Engagement mechanics that make learning intrinsically motivating and sticky." },
      { icon: "📈", title: "Learning Analytics", text: "Data dashboards that give educators real-time visibility into learner progress." },
      { icon: "🌐", title: "Offline-First Design", text: "Platforms built for South African realities — functional even without connectivity." },
    ],
    offerings: [
      { title: "Learner Management Systems", text: "Comprehensive LMS platforms for schools, colleges, and training providers." },
      { title: "Adaptive Learning Engines", text: "AI-powered content delivery that personalises the pace and style of learning." },
      { title: "Content Authoring Tools", text: "Giving educators powerful tools to create rich, interactive learning content." },
      { title: "Assessment Platforms", text: "Digital assessment tools with instant marking, analytics, and feedback loops." },
      { title: "Parent & Learner Portals", text: "Transparent progress tracking keeping all stakeholders informed and engaged." },
      { title: "EdTech Consulting", text: "Helping institutions select, implement, and optimise their technology ecosystems." },
    ],
    stats: [
      { num: "EdTech", label: "Specialist Focus" },
      { num: "K-12+", label: "Learning Levels" },
      { num: "2024", label: "Established" },
      { num: "∞", label: "Learners to Reach" },
    ],
    quote: "Technology doesn't replace the teacher. It gives the teacher superpowers. We build the cape.",
    quoteAttr: "Ace Group EdTech · Design Principle",
    desc: "Building EdTech platforms that make learning accessible, engaging, and measurable.",
  },
];

export const TUTORING_GRADES = [
  { grade: 8, price: 500 },
  { grade: 9, price: 650 },
  { grade: 10, price: 800 },
  { grade: 11, price: 950 },
  { grade: 12, price: 1100 },
];

export const TUTORING_SUBJECTS = [
  "Mathematics", "Physical Sciences", "Life Sciences", "English Home Language",
  "Afrikaans First Additional", "Geography", "History", "Accounting",
  "Business Studies", "Economics", "Computer Applications Technology",
  "Information Technology", "Mathematical Literacy", "Life Orientation",
];

export const SOFTWARE_SERVICES = [
  {
    id: "mobile",
    icon: "📱",
    title: "Mobile App Development",
    desc: "Native iOS & Android apps or cross-platform solutions using React Native and Flutter. Built for performance, scalability, and beautiful user experience.",
    pricing: "Request a Quote",
    features: ["iOS & Android", "React Native / Flutter", "UI/UX Design", "App Store Submission", "Ongoing Support"],
  },
  {
    id: "web",
    icon: "🌐",
    title: "Web Application Development",
    desc: "Full-stack web applications from landing pages to enterprise platforms. Built with modern frameworks and optimised for performance and SEO.",
    pricing: "Request a Quote",
    features: ["React / Next.js / Vue", "Node.js / FastAPI", "PostgreSQL / MongoDB", "Cloud Deployment", "Responsive Design"],
  },
  {
    id: "api",
    icon: "🔌",
    title: "API & Systems Integration",
    desc: "Connecting your systems through robust, secure APIs. We integrate third-party services, build internal APIs, and modernise legacy system connectivity.",
    pricing: "Request a Quote",
    features: ["REST & GraphQL APIs", "Third-party Integrations", "Webhook Automation", "API Documentation", "Rate Limiting & Auth"],
  },
  {
    id: "enterprise",
    icon: "🏢",
    title: "Enterprise Software",
    desc: "Mission-critical platforms for large organisations. ERP modules, CRM systems, workflow engines, and data management solutions built to enterprise grade.",
    pricing: "Request a Quote",
    features: ["Custom ERP / CRM", "Role-based Access Control", "Audit Trails", "Multi-tenant Architecture", "SLA-backed Delivery"],
  },
  {
    id: "devops",
    icon: "⚙️",
    title: "DevOps & Cloud Infrastructure",
    desc: "From CI/CD pipelines to cloud architecture, we design and manage your infrastructure so your team can ship faster with confidence.",
    pricing: "Request a Quote",
    features: ["AWS / Azure / GCP", "Docker & Kubernetes", "CI/CD Pipelines", "Monitoring & Alerting", "Infrastructure as Code"],
  },
  {
    id: "consulting",
    icon: "🧭",
    title: "Technical Consultancy",
    desc: "Strategic technology advice for product teams, startups, and enterprises. Architecture reviews, technology selection, team upskilling, and roadmap planning.",
    pricing: "Request a Quote",
    features: ["Architecture Reviews", "Tech Stack Selection", "Code Audits", "Team Mentoring", "Roadmap Planning"],
  },
];

export const TECH_STACK = [
  { icon: "⚛️", name: "React / Next.js", category: "Frontend" },
  { icon: "🐍", name: "Python / FastAPI", category: "Backend" },
  { icon: "📱", name: "React Native", category: "Mobile" },
  { icon: "🐘", name: "PostgreSQL", category: "Database" },
  { icon: "☁️", name: "AWS / EC2 / S3", category: "Cloud" },
  { icon: "🐳", name: "Docker", category: "DevOps" },
  { icon: "🔄", name: "n8n Automation", category: "Automation" },
  { icon: "🤖", name: "OpenAI / LLMs", category: "AI" },
];

export const BOOTCAMP_PHASES = [
  {
    number: "01",
    days: "Day 1–2",
    title: "Foundations",
    items: ["Introduction to Workflow Automation", "Understanding n8n architecture", "Nodes, triggers, webhooks", "Real-world automation examples"],
  },
  {
    number: "02",
    days: "Day 2–3",
    title: "APIs & Integration",
    items: ["What is an API", "REST APIs (GET, POST, PUT)", "Connecting n8n to external systems", "Build your first API workflow"],
  },
  {
    number: "03",
    days: "Day 3–4",
    title: "AI + LLM Integration",
    items: ["Introduction to Large Language Models", "Using OpenAI / Azure OpenAI in n8n", "Prompt engineering basics", "Building AI-powered workflows"],
  },
  {
    number: "04",
    days: "Day 4",
    title: "AI Agents in n8n",
    items: ["What are AI Agents", "Agent workflows using tools", "Memory + reasoning basics", "Build: Customer support agent, Invoice processing agent, Personal assistant"],
  },
  {
    number: "05",
    days: "Day 5",
    title: "Cloud Deployment",
    items: ["Intro to Amazon Web Services", "Deploy n8n on Amazon EC2", "Storage basics with Amazon S3", "Environment variables + secrets"],
  },
  {
    number: "06",
    days: "Advanced",
    title: "Backend + APIs",
    items: ["Introduction to FastAPI", "Build your own AI API", "Connect FastAPI → n8n", "Creating reusable automation services"],
  },
];
